import React, { useEffect, useState } from 'react'
import { faAngleDown, faAngleLeft, faBell, faClose, faComment, faFilter, faPlay, faShuffle } from '@fortawesome/free-solid-svg-icons'
import { NextPage } from 'next'
import Head from 'next/head'
import MenuButon, { BorderButon, MenuList } from '../src/components/Buton'
import DownButon from '../src/components/DownButon'
import Header from '../src/components/Header'
import styles from '../styles/Home.module.css'
import ArchiveMovieCover from '../src/components/ArchiveMovieCover'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Line from '../src/components/Line'
import MenuContainer from '../src/components/MenuContainer'
import { deleteContentNotification, getAnimes, getCategories, getMangas, postContentNotification } from '../src/utils/api'
import { AnimeFilter, AnimeModels, Categories, CategoryType, ContentNotification, MangaModels, Status, Type, VideoType } from '../src/types/Entites'
import { useDispatch, useSelector } from 'react-redux'
import { setAnimeFilter, setAnimeModels, setSelectedAnimeModel } from '../src/store/features/animeReducer'
import { RootState } from '../src/store'
import { Info } from './anime/[url]'
import StarRating from '../src/components/StarRating'
import { setMangaModels, setSelectedMangaModel } from '../src/store/features/mangaReducer'
import { useRouter } from 'next/router'
import LoadingScreen from '../src/components/LoadingScreen'
import FilterModal from '../src/components/FilterModal'
import { CommentCard } from '../src/components/Card'


const Archive: NextPage = () => {
  const dispatch = useDispatch();


  const [movieInfoShow, setMovieInfoShow] = useState(false);
  const [mangaInfoShow, setMangaInfoShow] = useState(false);
  const [selectedMenu, setSelectedMenu] = useState<MenuList>("Anime");
  const user = useSelector((x: RootState) => x.userReducer.value.user);
  const { animeModels, selectedAnimeModel, animeFilter } = useSelector((x: RootState) => x.animeReducer);
  const { mangaModels, selectedMangaModel } = useSelector((x: RootState) => x.mangaReducer);
  const [typeIsOpen, setTypeIsOpen] = useState<'show' | 'hide'>('hide');
  const [ratingIsOpen, setRatingIsOpen] = useState<'show' | 'hide'>('hide');
  const [rating, setRating] = useState(1);

  const [categoryIsOpen, setCategoryIsOpen] = useState<'show' | 'hide'>('hide');
  const [categories, setCategories] = useState<Array<Categories>>([]);

  const [loading, setLoading] = useState(true);
  const [filterModalIsShow, setFilterModalIsShow] = useState(false);
  useEffect(() => {
    setLoading(true);
    window.onpageshow = function (event) {
      if (event.persisted) {
        window.location.reload();
      }
    };
    setMovieInfoShow(false);
    if (selectedMenu === 'Anime') {
      loadAnimes();

    }
    else {
      loadMangas();
    }
    loadCategories();
    setLoading(false);
  }, [selectedMenu])
  const loadAnimes = async () => {
    await getAnimes().then((res) => {
      dispatch(setAnimeModels(res.data.list));
    }).catch((er) => {
      console.log(er);
    });
  }
  const loadMangas = async () => {
    await getMangas().then((res) => {
      dispatch(setMangaModels(res.data.list));
    })
  }
  const loadCategories = async () => {
    await getCategories().then((res) => {
      setCategories(res.data.list);
    })
  }
  return (
    <LoadingScreen loading={loading}>
      <div className={styles.archiveBackground}>
        <Head>
          <title>Arşiv</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header
          search={'show'}
          notification={'hide'}
          style={{ backgroundColor: '#141414', marginTop: 0, padding: '5px' }} />
        <div className={styles.archiveContainer}>
          <div style={{ height: '100%' }}>
            <MenuContainer>
              <div className={styles.leftMenuContainer} >
                <MenuButon marginright='10px' onClick={() => setSelectedMenu('Anime')} isactive={selectedMenu == "Anime" ? "T" : "F"} name='Anime' />
                <MenuButon marginright='10px' onClick={() => setSelectedMenu('Manga')} isactive={selectedMenu == "Manga" ? "T" : "F"} name='Manga' />
                <MenuButon width='45px' icon={faShuffle} />
                <MenuButon id="headerFilterButon" onClick={() => setFilterModalIsShow(true)} marginright='0px' width='45px' icon={faFilter} />
              </div>
              <div className={styles.rightMenuContainer}>
                <MenuButon marginright='10px' onClick={() => {
                  if (animeFilter.order === 'AZ') {
                    dispatch(setAnimeFilter({ ...animeFilter, order: null } as AnimeFilter))
                  }
                  else {
                    dispatch(setAnimeFilter({ ...animeFilter, order: 'AZ' } as AnimeFilter))
                  }
                }} isactive={animeFilter.order !== null ? "T" : "F"} name='A-Z' />
                <DownButon
                  show={categoryIsOpen} onClick={() => {
                    if (categoryIsOpen === "hide") {
                      setCategoryIsOpen('show')
                    }
                    else {
                      setCategoryIsOpen('hide')
                    }
                  }}
                  type="dropdown" icon={faAngleDown} name='Kategori'>
                  <div
                    onClick={() => {
                      dispatch(setAnimeFilter({ ...animeFilter, category: { id: 0 } } as AnimeFilter))
                    }}
                    className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.category.id === 0 && styles.listButonsActive)}>Tümü</div>
                  {
                    categories.length !== 0 &&
                    categories.map((item) => {
                      return <div
                        onClick={() => {
                          dispatch(setAnimeFilter({ ...animeFilter, category: item } as AnimeFilter))
                        }}
                        key={item.id} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.category.id === item.id && styles.listButonsActive)}>{item.name}</div>
                    })
                  }
                </DownButon>
                <DownButon show={typeIsOpen} onClick={() => {
                  if (typeIsOpen === "hide") {
                    setTypeIsOpen('show')
                  }
                  else {
                    setTypeIsOpen('hide')
                  }
                }} type="dropdown" icon={faAngleDown} name='Tür'>
                  <div onClick={() => {
                    dispatch(setAnimeFilter({ ...animeFilter, type: 0 } as AnimeFilter))
                  }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === 0 && styles.listButonsActive)}>Tümü</div>
                  <div onClick={() => {
                    dispatch(setAnimeFilter({ ...animeFilter, type: VideoType.AnimeMovie } as AnimeFilter))
                  }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === VideoType.AnimeMovie && styles.listButonsActive)}>Film</div>
                  <div onClick={() => {
                    dispatch(setAnimeFilter({ ...animeFilter, type: VideoType.AnimeSeries } as AnimeFilter))
                  }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === VideoType.AnimeSeries && styles.listButonsActive)}>Dizi</div>
                </DownButon>
                <DownButon show={ratingIsOpen} onClick={() => {
                  if (ratingIsOpen === "hide") {
                    setRatingIsOpen('show')
                  }
                  else {
                    setRatingIsOpen('hide')
                  }
                }} type="dropdown" icon={faAngleDown} name='Puan'>
                  <div style={{ display: 'flex', flex: 1, flexDirection: 'row', flexWrap: 'wrap' }}>
                    <StarRating rating={rating} handleRating={async (val: number) => {
                      setRating(val);
                    }} />
                  </div>
                </DownButon>
              </div>
            </MenuContainer>
            <div className={styles.contentContainer}>
              {
                selectedMenu === 'Anime' ?
                  [...animeModels].sort((a, b) => {
                    if (a.anime.animeName < b.anime.animeName) {
                      return 1;
                    }
                    return -1;
                  }).filter((y) => {
                    return y;
                  }).map((item) => {
                    return <ArchiveMovieCover
                      alt={item.anime.animeName}
                      src={item.anime.img}
                      blur={Object.keys(selectedAnimeModel).length === 0 ? "1" : selectedAnimeModel.anime.id !== item.anime.id ? "0" : "1"}
                      onClick={() => {
                        if (Object.keys(user).length !== 0) {
                          setMovieInfoShow(true)
                          dispatch(setSelectedAnimeModel(item));
                        }
                      }}
                      show={Object.keys(selectedAnimeModel).length != 0 && selectedAnimeModel.anime.id === item.anime.id ? "1" : undefined} key={item.anime.id} />
                  })
                  :
                  mangaModels.sort((a, b) => {
                    if (a.manga.name < b.manga.name) {
                      return 1;
                    }
                    return -1;
                  }).filter((y) => {
                    return y;
                  }).map((item) => {
                    return <ArchiveMovieCover
                      alt={item.manga.name}
                      src={item.manga.image}
                      blur={Object.keys(selectedMangaModel).length === 0 ? "1" : selectedMangaModel.manga.id !== item.manga.id ? "0" : "1"}
                      onClick={() => {
                        if (Object.keys(user).length !== 0) {
                          setMangaInfoShow(true)
                          dispatch(setSelectedMangaModel(item));
                        }
                      }}
                      show={Object.keys(selectedMangaModel).length != 0 && selectedMangaModel.manga.id === item.manga.id ? "1" : undefined} key={item.manga.id} />
                  })
              }
            </div>
          </div>

        </div>
        {filterModalIsShow && <FilterModal onClick={() => setFilterModalIsShow(false)}>
          <DownButon
            show={categoryIsOpen} onClick={() => {
              if (categoryIsOpen === "hide") {
                setCategoryIsOpen('show')
              }
              else {
                setCategoryIsOpen('hide')
              }
            }}
            type="dropdown" icon={faAngleDown} name='Kategori'>
            <div
              onClick={() => {
                dispatch(setAnimeFilter({ ...animeFilter, category: { id: 0 } } as AnimeFilter))
              }}
              className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.category.id === 0 && styles.listButonsActive)}>Tümü</div>
            {
              categories.length !== 0 &&
              categories.map((item) => {
                return <div
                  onClick={() => {
                    dispatch(setAnimeFilter({ ...animeFilter, category: item } as AnimeFilter))
                  }}
                  key={item.id} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.category.id === item.id && styles.listButonsActive)}>{item.name}</div>
              })
            }
          </DownButon>
          <div style={{ marginTop: '10px', marginBottom: '10px' }}>
            <DownButon show={typeIsOpen} onClick={() => {
              if (typeIsOpen === "hide") {
                setTypeIsOpen('show')
              }
              else {
                setTypeIsOpen('hide')
              }
            }} type="dropdown" icon={faAngleDown} name='Tür'>
              <div onClick={() => {
                dispatch(setAnimeFilter({ ...animeFilter, type: 0 } as AnimeFilter))
              }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === 0 && styles.listButonsActive)}>Tümü</div>
              <div onClick={() => {
                dispatch(setAnimeFilter({ ...animeFilter, type: VideoType.AnimeMovie } as AnimeFilter))
              }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === VideoType.AnimeMovie && styles.listButonsActive)}>Film</div>
              <div onClick={() => {
                dispatch(setAnimeFilter({ ...animeFilter, type: VideoType.AnimeSeries } as AnimeFilter))
              }} className={styles.listButons + " " + styles.userSelected + " " + (animeFilter.type === VideoType.AnimeSeries && styles.listButonsActive)}>Dizi</div>
            </DownButon>
          </div>
          <div style={{ marginTop: '10px', marginBottom: '10px' }}>
            <DownButon show={ratingIsOpen} onClick={() => {
              if (ratingIsOpen === "hide") {
                setRatingIsOpen('show')
              }
              else {
                setRatingIsOpen('hide')
              }
            }} type="dropdown" icon={faAngleDown} name='Puan'>
              <div style={{ display: 'flex', flex: 1, flexDirection: 'row', flexWrap: 'wrap' }}>
                <StarRating rating={rating} handleRating={async (val: number) => {
                  setRating(val);
                }} />
              </div>
            </DownButon>
          </div>
          <div style={{ marginTop: '10px', marginBottom: '10px', marginLeft: '10px', marginRight: '5px' }}>
            <MenuButon marginright='0px' onClick={() => {
              if (animeFilter.order === 'AZ') {
                dispatch(setAnimeFilter({ ...animeFilter, order: null } as AnimeFilter))
              }
              else {
                dispatch(setAnimeFilter({ ...animeFilter, order: 'AZ' } as AnimeFilter))
              }
            }} isactive={animeFilter.order !== null ? "T" : "F"} name='A-Z' />
          </div>
        </FilterModal>}
        {movieInfoShow && <MovieDescriptionModal handleCloseModal={() => setMovieInfoShow(false)} />}
        {mangaInfoShow && <MangaDescriptionModal handleCloseModal={() => setMangaInfoShow(false)} />}
      </div>
    </LoadingScreen>
  )
}
export default Archive;

const MovieDescriptionModal = (props: { handleCloseModal: () => void }) => {
  var navigate = useRouter();
  const dispatch = useDispatch();
  const user = useSelector((x: RootState) => x.userReducer.value.user);
  const { selectedAnimeModel } = useSelector((x: RootState) => x.animeReducer);
  const [type, setType] = useState('DETAIL' || 'COMMENT');
  const ModalTitleContainer = () => {
    return (
      <div className={styles.titleContainer}>
        <div className={styles.detailsHeader}>
          <h2>{selectedAnimeModel.anime.animeName}</h2>
          <div
            onClick={async () => {
              if (selectedAnimeModel.contentNotification === null) {
                await postContentNotification({ userID: user.id, contentID: selectedAnimeModel.anime.id, type: Type.Anime } as ContentNotification).then((res) => {
                  dispatch(setSelectedAnimeModel({ ...selectedAnimeModel, contentNotification: res.data.entity } as AnimeModels));
                })
              }
              else {
                await deleteContentNotification(selectedAnimeModel.contentNotification.id).then((res) => {
                  if (res.data.isSuccessful) {
                    dispatch(setSelectedAnimeModel({ ...selectedAnimeModel, contentNotification: res.data.entity } as AnimeModels));
                  }
                })
              }
            }}
            className={styles.movieNotification}>
            <FontAwesomeIcon fontSize="20px" icon={faBell} color={selectedAnimeModel.contentNotification === null ? "rgba(255,255,255,0.5)" : "rgb(253, 188, 11)"} />
          </div>
        </div>


        <div style={{ marginBottom: '10px' }}></div>
        <Line />
      </div>
    )
  }
  const ModalBodyContainer = () => {
    return (
      <div className={styles.bodyContainer}>
        {
          type === 'DETAIL' ?
            selectedAnimeModel.anime.animeDescription
            :
            selectedAnimeModel.comments !== undefined && selectedAnimeModel.comments.length !== 0 ?
              <div className={styles.discoverCommentContainer}>
                {
                  selectedAnimeModel.comments.map((item, index) => {
                    return <CommentCard key={index} item={item} />
                  })
                }
              </div>
              :
              <div style={{ display: 'flex', justifyContent: 'center' }}>Yorum bulunamadı</div>
        }
      </div>
    )
  }
  const ModalFooterContainer = () => {
    return (
      <div className={styles.footerContainer}>
        {type === 'DETAIL' ? <a
          onClick={() => {
            navigate.push("/anime/" + selectedAnimeModel.anime.seoUrl)
          }}>
          <FontAwesomeIcon color='#ffffff60' icon={faPlay} />
        </a>
          :
          <a onClick={() => setType('DETAIL')}>
            <FontAwesomeIcon color='#ffffff60' icon={faAngleLeft} />
          </a>
        }
        {type !== 'COMMENT' && <a onClick={() => setType('COMMENT')}><FontAwesomeIcon color='#ffffff60' icon={faComment} /></a>}
      </div>
    )
  }
  return (
    <div className={styles.infoModalDescriptionModal}>
      <div className={styles.infoModalContent}>
        <div style={{ flex: 1, display: 'flex', justifyContent: 'flex-end' }}>
          <div className={styles.infoModalCloseContainer}
            onClick={() => {
              dispatch(setSelectedAnimeModel({}));
              props.handleCloseModal();

            }}>
            <FontAwesomeIcon icon={faClose} color={"#fff"} size={"2x"} />
          </div>
        </div>
        {type === 'DETAIL' ?
          <div>
            <ModalTitleContainer />
            <div className={styles.infoHeaderContainer}>
              {
                selectedAnimeModel.categories !== undefined &&
                selectedAnimeModel.categories.map((item) => {
                  return <Info key={item.id} name={item.categories.name} />
                })
              }
              <Info name={'Mal: ' + selectedAnimeModel.anime.malRating} />
              <Info name={'Bölümler: ' + selectedAnimeModel.animeEpisodes.length} />
              <Info name={"Yaş Sınırı: " + selectedAnimeModel.anime.ageLimit} />
              <Info name={'Beğeni: ' + selectedAnimeModel.likeCount} />
              <Info name={'Site: ' + selectedAnimeModel.anime.siteRating} />
              <Info name={'Çıkış: ' + selectedAnimeModel.anime.showTime} />
              <Info name={selectedAnimeModel.anime.videoType === VideoType.AnimeSeries ? "Tür: Dizi" : "Tür: Film"} />
              <Info name={'Sıralama: ' + selectedAnimeModel.arrangement} />
              <Info name={'Sezon Sayısı: ' + selectedAnimeModel.anime.seasonCount} />
              <Info name={'İzlenme: ' + selectedAnimeModel.viewsCount} />
              <Info name={selectedAnimeModel.anime.status === Status.Continues ? "Durumu: Devam Ediyor" : "Durumu: Bitti"} />
            </div>
            <div className={styles.infoLineContainer}>
              <Line />
            </div>
            <ModalBodyContainer />
          </div>
          : <ModalBodyContainer />
        }
        <ModalFooterContainer />
      </div>
    </div>
  )
}
const MangaDescriptionModal = (props: { handleCloseModal: () => void }) => {
  const dispatch = useDispatch();
  const navigate = useRouter();
  const user = useSelector((x: RootState) => x.userReducer.value.user);
  const { selectedMangaModel } = useSelector((x: RootState) => x.mangaReducer);
  const [type, setType] = useState('DETAIL' || 'COMMENT');
  const ModalTitleContainer = () => {
    return (
      <div className={styles.titleContainer}>
        <div className={styles.detailsHeader}>
          <h2>{selectedMangaModel.manga.name}</h2>
          <div
            onClick={async () => {
              if (selectedMangaModel.contentNotification === null) {
                await postContentNotification({ userID: user.id, contentID: selectedMangaModel.manga.id, type: Type.Anime } as ContentNotification).then((res) => {
                  dispatch(setSelectedMangaModel({ ...selectedMangaModel, contentNotification: res.data.entity } as MangaModels));
                })
              }
              else {
                await deleteContentNotification(selectedMangaModel.contentNotification.id).then((res) => {
                  if (res.data.isSuccessful) {
                    dispatch(setSelectedMangaModel({ ...selectedMangaModel, contentNotification: res.data.entity } as MangaModels));
                  }
                })
              }
            }}
            className={styles.movieNotification}>
            <FontAwesomeIcon fontSize="20px" icon={faBell} color={selectedMangaModel.contentNotification === null ? "rgba(255,255,255,0.5)" : "rgb(253, 188, 11)"} />
          </div>
        </div>


        <div style={{ marginBottom: '10px' }}></div>
        <Line />
      </div>
    )
  }
  const ModalBodyContainer = () => {
    return (
      <div className={styles.bodyContainer}>
        {
          type === 'DETAIL' ?
            selectedMangaModel.manga.description
            :
            selectedMangaModel.comments !== undefined && selectedMangaModel.comments.length !== 0 ?
              <div className={styles.discoverCommentContainer}>
                {
                  selectedMangaModel.comments.map((item, index) => {
                    return <CommentCard key={index} item={item} />
                  })
                }
              </div>
              :
              <div style={{ display: 'flex', justifyContent: 'center' }}>Yorum bulunamadı</div>
        }
      </div>
    )
  }
  const ModalFooterContainer = () => {
    return (
      <div className={styles.footerContainer}>
        {type === 'DETAIL' ? <a onClick={() => {
          navigate.push("/manga/" + selectedMangaModel.manga.seoUrl)
        }}><FontAwesomeIcon color='#ffffff60' icon={faPlay} /></a>
          :
          <div onClick={() => setType('DETAIL')}><FontAwesomeIcon color='#ffffff60' icon={faAngleLeft} /></div>
        }
        {type !== 'COMMENT' && <div onClick={() => setType('COMMENT')}><FontAwesomeIcon color='#ffffff60' icon={faComment} /></div>}
      </div>
    )
  }
  return (
    <div className={styles.infoModalDescriptionModal}>
      <div className={styles.infoModalContent}>
        <div style={{ flex: 1, display: 'flex', justifyContent: 'flex-end' }}>
          <div className={styles.infoModalCloseContainer}
            onClick={() => {
              dispatch(setSelectedMangaModel({}));
              props.handleCloseModal();

            }}>
            <FontAwesomeIcon icon={faClose} color={"#fff"} size={"2x"} />
          </div>
        </div>
        {
          type === 'DETAIL' &&
          <div>
            <ModalTitleContainer />
            <div className={styles.infoHeaderContainer}>
              {
                selectedMangaModel.categories !== undefined &&
                selectedMangaModel.categories.map((item) => {
                  return <Info key={item.id} name={item.categories.name} />
                })
              }
              <Info name={'Bölümler: ' + selectedMangaModel.mangaEpisodeCount} />
              <Info name={"Yaş Sınırı: " + selectedMangaModel.manga.ageLimit} />
              <Info name={'Beğeni: ' + selectedMangaModel.likeCount} />
              <Info name={'Sıralama: ' + selectedMangaModel.arrangement} />
              <Info name={'Sezon Sayısı: ' + selectedMangaModel.mangaEpisodeCount} />
              <Info name={'İzlenme: ' + selectedMangaModel.viewsCount} />
              <Info name={selectedMangaModel.manga.status === Status.Continues ? "Durumu: Devam Ediyor" : "Durumu: Bitti"} />
            </div>
            <div className={styles.infoLineContainer}>
              <Line />
            </div>
          </div>
        }
        <ModalBodyContainer />
        <ModalFooterContainer />
      </div>
    </div>
  )
}