import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../src/components/Header'
import styles from '../styles/Home.module.css'

const Deneme: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <div>
                <Image src={"/bgImage.png"} layout="fill" />
            </div>
        </div>
    )
}

export default Deneme;
