import Head from 'next/head';
import React, { useEffect, useState } from 'react'
import MenuButon, { MenuList } from '../src/components/Buton';
import DownButon from '../src/components/DownButon';
import Header from '../src/components/Header';
import MenuContainer from '../src/components/MenuContainer';
import styles from '../styles/Home.module.css';
import { faAngleDown, faComment, faSearch, faShuffle, faThumbsUp, faWarning } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Line from '../src/components/Line';
import { FanArtCard } from '../src/components/Card';
import { useAuth } from '../src/hooks/useAuth';
export default function Discover() {
  const { user } = useAuth();
  const [loggedUser, setLoggedUser] = useState({});
  useEffect(() => {
    setLoggedUser(user)
  }, [user])

  const [selectedMenu, setSelectedMenu] = useState<MenuList>("Anime");
  const Top100Card = () => {
    return (
      <div className={styles.top100Card}>
        <div className={styles.top100Img}>
          <img height={53} width={43} src={"http://localhost:3000/movieImg.png"} />
        </div>
        <div className={styles.topBody}>
          <span> Banana Fish</span>
          <span className={styles.topViewCount}>
            49817 görüntülenme
          </span>
        </div>
        <div className={styles.topNumber}>
          <h1>1</h1>
        </div>
      </div>
    )
  }
  return (
    <div className={styles.archiveBackground}>
      <Head>
        <title>Keşfet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        search={'show'}
        notification={'hide'}
        style={{ backgroundColor: '#141414', marginTop: 0, padding: '5px' }} />
      <div className={styles.archiveContainer}>
        <div style={{ height: '100%' }}>
          <MenuContainer>
            <div className={styles.leftMenuContainer} >
              <MenuButon marginright='10px' onClick={() => setSelectedMenu('Anime')} isactive={selectedMenu == "Anime" ? "T" : "F"} name='Anime' />
              <MenuButon marginright='10px' onClick={() => setSelectedMenu('Manga')} isactive={selectedMenu == "Manga" ? "T" : "F"} name='Manga' />
              <MenuButon width='45px' icon={faShuffle} />
              <div className={styles.discoverSearchContainer}>
                <div className={styles.searchIcon}>
                  <FontAwesomeIcon fontSize={14} icon={faSearch} color={"rgba(255,255,255,0.50)"} />
                </div>
                <input type={"text"} />
              </div>
            </div>
            <div className={styles.rightMenuContainer}>
              <DownButon type="buton" icon={faAngleDown} name='Oluştur' />
              <DownButon type="buton" icon={faAngleDown} name='Tarih' />
              <DownButon type="buton" icon={faAngleDown} name='Kategori' />
              <DownButon type="buton" icon={faAngleDown} name='Tür' />
              <DownButon type="buton" icon={faAngleDown} name='Popülerite' />
            </div>
          </MenuContainer>
          <div className={styles.discoverContainer}>
            <div className={styles.discoverLeft}>
              <div className={styles.discoverReview}>
                <img src='http://localhost:3000/Layout.png' />
              </div>
              <div className={styles.discoverDivider}>
                <span></span>
              </div>
              <div className={styles.discoverFanArt}>
                <img src='http://localhost:3000/Palette.svg' />
              </div>
            </div>
            <div className={styles.discoverMiddle}>
              <ReviewCard animeImgShow={true} />
              <ReviewCard animeImgShow={false} />
              <ReviewCard animeImgShow={true} />
              <ReviewCard animeImgShow={true} />
              <ReviewCard animeImgShow={false} />
              <div style={{ display: 'flex', flexDirection: 'column', gap: 30 }}>
                <FanArtCard user={loggedUser} />
                <FanArtCard user={loggedUser} />
                <FanArtCard user={loggedUser} />
                <FanArtCard user={loggedUser} />
                <FanArtCard user={loggedUser} />
              </div>
            </div>
            <div className={styles.discoverRight}>
              <div className={styles.weekAnime}>
                <div className={styles.weekAnimeHeader}>
                  <h3>Haftanın Animesi</h3>
                  <Line />
                </div>
                <div className={styles.weekAnimeBody}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute iru
                  re dolor in reprehenderit in voluptate velit esse cillum dolore e
                  u fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                  proident, sunt in culpa qui officia deserunt mollit anim id est la
                  borum. Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                  sed do eiusmod tempor incididunt ut labore et dolore magna
                  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul
                  lamco laboris nisi ut aliquip ex ea commodo consequat. Duis a
                  ute irure dolor in reprehenderit in voluptate velit esse cillum...

                </div>
              </div>
              <div className={styles.top100}>
                <div className={styles.top100Header}>
                  <h3>Top 100</h3>
                  <Line />
                </div>
                <div className={styles.top100Body}>
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                  <Top100Card />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
const ReviewCard = (props: {
  animeImgShow: boolean
}) => {

  return (
    <div className={styles.fanArtContainer}>
      <div className={styles.fanArtContainerImg}>
        <div className={styles.fanArtImg}>
          <div className={styles.shareUserName}><a>erayatmaca</a></div>
          <img src='http://localhost:3000/cerceve.png' />
        </div>
        <div className={styles.ImgDivider}></div>
      </div>
      <div className={styles.fanArtBody}>
        {props.animeImgShow && <div style={{ paddingRight: '10px' }}>
          <img height={100} width={80} src={"http://localhost:3000/movieImg.png"} />
        </div>}
        <div>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ...
        </div>
      </div>
      <div className={styles.fanArtRight}>
        <div style={{ paddingRight: '10px' }}>
          <div className={styles.ImgDivider}></div>
        </div>
        <div>
          <div className={styles.fanArtIconButons}>
            <FontAwesomeIcon fontSize={15} color='rgba(255, 255, 255, 0.50)' icon={faWarning} />
          </div>
          <div className={styles.fanArtIconButons}>
            <FontAwesomeIcon fontSize={15} color='rgba(255, 255, 255, 0.50)' icon={faComment} />
          </div>
          <div className={styles.fanArtIconButons}>
            <FontAwesomeIcon fontSize={15} color='rgba(255, 255, 255, 0.50)' icon={faThumbsUp} />
          </div>
        </div>
      </div>
    </div>
  )
}
