import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/Header'
import Movie from '../src/components/Movie'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Ana sayfa</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomePage />
        <MoviesPage />
      </div>
    </div>
  )
}
export default Home;



const HomePage = () => {
  return (
    <div className={styles.pageContainer}>
      <HomeSlider>
        <Header  />
        {/* <SiteAnimeModal /> */}
      </HomeSlider>
    </div>
  )
}
const MoviesPage = () => {
  return (
    <div className={styles.pageContainer + " " + styles.homePage2}>
      <div className={styles.leftContainer}><h4>Popüler Seriler</h4></div>
      <div className={styles.rightContainer}><h4>Yeni Bölümler</h4></div>
      <div style={{ position: "absolute", left: 0 }}>
        <div style={{ position: 'relative', display: 'flex', flex: 1, top: 190 }}>
          <Movie marginLeft='20px' src="http://localhost:3000/movieImg1.png" />
          <Movie marginLeft='27px' src="http://localhost:3000/movieImg.png" />
          <Movie marginLeft='27px' src="http://localhost:3000/movieImg1.png" />
          <Movie marginLeft='27px' src="http://localhost:3000/movieImg.png" />
        </div>
        {/* <div style={{ position: 'relative', display: 'flex', flex: 1, top: 350, marginLeft: 0 }}>
          <Movie src="http://localhost:3000/movieImg.png" />
          <Movie src="http://localhost:3000/movieImg1.png" />
          <Movie src="http://localhost:3000/movieImg.png" />
          <Movie src="http://localhost:3000/movieImg1.png" />
        </div> */}
      </div>
      {/* <div style={{ position: "absolute", right: 0 }}>
        <div style={{ position: 'relative', display: 'flex', flex: 1, top: 195 }}>
          <Movie src="http://localhost:3000/movieImg1.png" />
          <Movie src="http://localhost:3000/movieImg.png" />
          <Movie src="http://localhost:3000/movieImg1.png" />
          <Movie src="http://localhost:3000/movieImg.png" />
        </div>
        <div style={{ position: 'relative', display: 'flex', flex: 1, top: 230, marginRight: 10 }}>
          <Movie src="http://localhost:3000/movieImg.png" />
          <Movie src="http://localhost:3000/movieImg1.png" />
          <Movie src="http://localhost:3000/movieImg.png" />
          <Movie src="http://localhost:3000/movieImg1.png" />
        </div>
      </div> */}
    </div>
  )
}
const HomeSlider = (props: { children: React.ReactNode }) => {
  const SliderDescription = () => {
    return (
      <div className={styles.homeSliderDescription}>
        <div className={styles.homeSliderDescriptionContainer}>
          <div className={styles.homeSliderDescriptionTitle}>
            <h2>Shingeki no Kyojin</h2>
          </div>
          <span><img src="/playButons.png" className={styles.playButons} /></span>
        </div>
        <div className={styles.homeSliderDescriptionContent}>
          Yüzyıllar evvel insanoğlu devler tarafından yok olmanın eşiğine getirilmiştir. Devler tıpkı anlatılagelmiş hikayelerdeki gibi, uzun, zekadan yoksun görünen, insanları yiyen ve de en kötüsü bunu beslenmek için değil zevk için yapan varlıklardır.
        </div>
      </div>
    )
  }
  const SliderButons = () => {
    return (
      <div className={styles.sliderButonsContainer}>
        <div className={styles.sliderButons}></div>
        <div className={styles.sliderButons}></div>
        <div className={styles.sliderButons}></div>
        <div className={styles.sliderButons}></div>
        <div className={styles.sliderButons}></div>
      </div>
    )
  }
  return (
    <div className={styles.homeBg} style={{
      background: 'linear-gradient(0deg, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0.15)), linear-gradient(90.16deg, rgba(0, 0, 0, 0.5) 50.68%, rgba(0, 0, 0, 0) 70.09%),url("http://localhost:3000/bgImage.png")',
    }}>
      {props.children}
      <SliderDescription />
      <SliderButons />
    </div >
  )
}